!!scenarios.ScenarioConfig
name: "Escenario con mucha demanda"
description: "Escenario con mucha demanda y poca oferta."
clock:
  unitTimeMillis: 1000
  numUnitDay: 10
  numSimDays: 3
fishMarket:
  name: "Lonja"
  config: "configs/standardfishMarket.yaml"
buyers:
  - name: "Comprador1"
    config: "configs/buyerType1.yaml"
  - name: "Comprador2"
    config: "configs/buyerType1.yaml"
  - name: "Comprador3"
    config: "configs/buyerType1.yaml"
  - name: "Comprador4"
    config: "configs/buyerType1.yaml"
  - name: "Comprador5"
    config: "configs/buyerType1.yaml"
sellers:
  - name: "Vendedor1"
    config: "configs/sellerType1.yaml"

