!!scenarios.ScenarioConfig
name: "Escenario con una cinta"
description: "Escenario con una cinta."
clock:
  unitTimeMillis: 1000
  numUnitDay: 10
  numSimDays: 3
fishMarket:
  name: "Lonja"
  config: "configs/oneLaneFishMarket.yaml"
buyers:
  - name: "Comprador1"
    config: "configs/buyerType1.yaml"
  - name: "Comprador2"
    config: "configs/buyerType2.yaml"
  - name: "Comprador3"
    config: "configs/buyerType3.yaml"
sellers:
  - name: "Vendedor1"
    config: "configs/sellerType1.yaml"
  - name: "Vendedor2"
    config: "configs/sellerType2.yaml"


